import type { WorkbookData, SheetData, ColumnMetadata } from './dataEngine';

function createMockWorkbook(sheetName: string, rows: any[]): WorkbookData {
  const columnSet = new Set<string>();
  rows.forEach(row => {
    Object.keys(row).forEach(key => columnSet.add(key));
  });
  const columnNames = Array.from(columnSet);

  const columns: ColumnMetadata[] = columnNames.map(colName => {
    const values = rows
      .map(row => row[colName])
      .filter(val => val !== null && val !== undefined && val !== '');

    const nullCount = rows.length - values.length;
    let type: 'number' | 'string' | 'date' | 'boolean' = 'string';

    if (values.length > 0) {
      const firstVal = values[0];
      if (typeof firstVal === 'number') {
        type = 'number';
      } else if (firstVal instanceof Date) {
        type = 'date';
      } else if (typeof firstVal === 'boolean') {
        type = 'boolean';
      } else {
        const allNumeric = values.every(v => !isNaN(Number(v)) && typeof v !== 'boolean');
        if (allNumeric) {
          type = 'number';
        }
      }
    }

    const uniqueVals = new Set(values.map(v => (v instanceof Date ? v.getTime() : v)));
    const uniqueCount = uniqueVals.size;

    let min: any = undefined;
    let max: any = undefined;
    let avg: number | undefined = undefined;

    if (type === 'number') {
      const numericValues = values.map(v => Number(v)).filter(v => !isNaN(v));
      if (numericValues.length > 0) {
        min = Math.min(...numericValues);
        max = Math.max(...numericValues);
        const sum = numericValues.reduce((a, b) => a + b, 0);
        avg = Number((sum / numericValues.length).toFixed(2));
      }
    }

    return {
      name: colName,
      type,
      uniqueCount,
      nullCount,
      min,
      max,
      avg
    };
  });

  const sheet: SheetData = {
    name: sheetName,
    rows,
    columns,
    rowCount: rows.length
  };

  return {
    sheets: [sheet],
    activeSheetName: sheetName
  };
}

// 1. PEMT Data (Public Emergency Medical Transportation)
const pemtRows = [
  { Month: 'July 2024', 'Run Volume': 1250, 'Transport Fee': 450, 'Avg Cost Per Transport': 620, 'Total Revenue': 562500, 'PEMT Supplement': 212500 },
  { Month: 'August 2024', 'Run Volume': 1310, 'Transport Fee': 450, 'Avg Cost Per Transport': 615, 'Total Revenue': 589500, 'PEMT Supplement': 216000 },
  { Month: 'September 2024', 'Run Volume': 1190, 'Transport Fee': 450, 'Avg Cost Per Transport': 630, 'Total Revenue': 535500, 'PEMT Supplement': 214200 },
  { Month: 'October 2024', 'Run Volume': 1420, 'Transport Fee': 460, 'Avg Cost Per Transport': 605, 'Total Revenue': 653200, 'PEMT Supplement': 206000 },
  { Month: 'November 2024', 'Run Volume': 1280, 'Transport Fee': 460, 'Avg Cost Per Transport': 625, 'Total Revenue': 588800, 'PEMT Supplement': 211000 },
  { Month: 'December 2024', 'Run Volume': 1350, 'Transport Fee': 460, 'Avg Cost Per Transport': 620, 'Total Revenue': 621000, 'PEMT Supplement': 215000 },
  { Month: 'January 2025', 'Run Volume': 1410, 'Transport Fee': 470, 'Avg Cost Per Transport': 610, 'Total Revenue': 662700, 'PEMT Supplement': 198000 },
  { Month: 'February 2025', 'Run Volume': 1200, 'Transport Fee': 470, 'Avg Cost Per Transport': 635, 'Total Revenue': 564000, 'PEMT Supplement': 198000 },
  { Month: 'March 2025', 'Run Volume': 1330, 'Transport Fee': 470, 'Avg Cost Per Transport': 615, 'Total Revenue': 625100, 'PEMT Supplement': 193000 },
  { Month: 'April 2025', 'Run Volume': 1290, 'Transport Fee': 470, 'Avg Cost Per Transport': 620, 'Total Revenue': 606300, 'PEMT Supplement': 193500 },
  { Month: 'May 2025', 'Run Volume': 1380, 'Transport Fee': 480, 'Avg Cost Per Transport': 610, 'Total Revenue': 662400, 'PEMT Supplement': 179400 },
  { Month: 'June 2025', 'Run Volume': 1450, 'Transport Fee': 480, 'Avg Cost Per Transport': 600, 'Total Revenue': 696000, 'PEMT Supplement': 174000 }
];

// 2. Personnel Hours and Pay
const personnelRows = [
  // EMT-Basic
  { 'Employee ID': 'EMP-001', 'Job Title': 'EMT-Basic', 'FTE Count': 1.0, 'Avg Hourly Rate': 23.50, 'Regular Hours': 2080, 'Overtime Hours': 120, 'Total Regular Pay': 48880, 'Total Overtime Pay': 4230 },
  { 'Employee ID': 'EMP-002', 'Job Title': 'EMT-Basic', 'FTE Count': 1.0, 'Avg Hourly Rate': 24.00, 'Regular Hours': 2080, 'Overtime Hours': 250, 'Total Regular Pay': 49920, 'Total Overtime Pay': 9000 },
  { 'Employee ID': 'EMP-003', 'Job Title': 'EMT-Basic', 'FTE Count': 1.0, 'Avg Hourly Rate': 25.50, 'Regular Hours': 2080, 'Overtime Hours': 450, 'Total Regular Pay': 53040, 'Total Overtime Pay': 17210 },
  { 'Employee ID': 'EMP-004', 'Job Title': 'EMT-Basic', 'FTE Count': 1.0, 'Avg Hourly Rate': 22.00, 'Regular Hours': 2080, 'Overtime Hours': 80, 'Total Regular Pay': 45760, 'Total Overtime Pay': 2640 },
  { 'Employee ID': 'EMP-005', 'Job Title': 'EMT-Basic', 'FTE Count': 1.0, 'Avg Hourly Rate': 28.50, 'Regular Hours': 2080, 'Overtime Hours': 320, 'Total Regular Pay': 59280, 'Total Overtime Pay': 13680 },
  { 'Employee ID': 'EMP-006', 'Job Title': 'EMT-Basic', 'FTE Count': 0.5, 'Avg Hourly Rate': 24.50, 'Regular Hours': 1040, 'Overtime Hours': 40, 'Total Regular Pay': 25480, 'Total Overtime Pay': 1470 },
  { 'Employee ID': 'EMP-007', 'Job Title': 'EMT-Basic', 'FTE Count': 1.0, 'Avg Hourly Rate': 23.00, 'Regular Hours': 2080, 'Overtime Hours': 180, 'Total Regular Pay': 47840, 'Total Overtime Pay': 6210 },
  { 'Employee ID': 'EMP-008', 'Job Title': 'EMT-Basic', 'FTE Count': 1.0, 'Avg Hourly Rate': 24.50, 'Regular Hours': 2080, 'Overtime Hours': 290, 'Total Regular Pay': 50960, 'Total Overtime Pay': 10650 },
  { 'Employee ID': 'EMP-009', 'Job Title': 'EMT-Basic', 'FTE Count': 1.0, 'Avg Hourly Rate': 26.00, 'Regular Hours': 2080, 'Overtime Hours': 310, 'Total Regular Pay': 54080, 'Total Overtime Pay': 12090 },
  { 'Employee ID': 'EMP-010', 'Job Title': 'EMT-Basic', 'FTE Count': 1.0, 'Avg Hourly Rate': 15.00, 'Regular Hours': 2080, 'Overtime Hours': 150, 'Total Regular Pay': 31200, 'Total Overtime Pay': 3375 },
  { 'Employee ID': 'EMP-011', 'Job Title': 'EMT-Basic', 'FTE Count': 1.0, 'Avg Hourly Rate': 25.00, 'Regular Hours': 2080, 'Overtime Hours': 140, 'Total Regular Pay': 52000, 'Total Overtime Pay': 5250 },
  { 'Employee ID': 'EMP-012', 'Job Title': 'EMT-Basic', 'FTE Count': 1.0, 'Avg Hourly Rate': 23.50, 'Regular Hours': 2080, 'Overtime Hours': 200, 'Total Regular Pay': 48880, 'Total Overtime Pay': 7050 },

  // Paramedic
  { 'Employee ID': 'EMP-013', 'Job Title': 'Paramedic', 'FTE Count': 1.0, 'Avg Hourly Rate': 30.50, 'Regular Hours': 2080, 'Overtime Hours': 310, 'Total Regular Pay': 63440, 'Total Overtime Pay': 14180 },
  { 'Employee ID': 'EMP-014', 'Job Title': 'Paramedic', 'FTE Count': 1.0, 'Avg Hourly Rate': 32.00, 'Regular Hours': 2080, 'Overtime Hours': 420, 'Total Regular Pay': 66560, 'Total Overtime Pay': 20160 },
  { 'Employee ID': 'EMP-015', 'Job Title': 'Paramedic', 'FTE Count': 1.0, 'Avg Hourly Rate': 29.50, 'Regular Hours': 2080, 'Overtime Hours': 150, 'Total Regular Pay': 61360, 'Total Overtime Pay': 6630 },
  { 'Employee ID': 'EMP-016', 'Job Title': 'Paramedic', 'FTE Count': 1.0, 'Avg Hourly Rate': 34.00, 'Regular Hours': 2080, 'Overtime Hours': 480, 'Total Regular Pay': 70720, 'Total Overtime Pay': 24480 },
  { 'Employee ID': 'EMP-017', 'Job Title': 'Paramedic', 'FTE Count': 1.0, 'Avg Hourly Rate': 31.00, 'Regular Hours': 2080, 'Overtime Hours': 220, 'Total Regular Pay': 64480, 'Total Overtime Pay': 10230 },
  { 'Employee ID': 'EMP-018', 'Job Title': 'Paramedic', 'FTE Count': 1.0, 'Avg Hourly Rate': 28.00, 'Regular Hours': 2080, 'Overtime Hours': 180, 'Total Regular Pay': 58240, 'Total Overtime Pay': 7560 },
  { 'Employee ID': 'EMP-019', 'Job Title': 'Paramedic', 'FTE Count': 1.0, 'Avg Hourly Rate': 31.50, 'Regular Hours': 2080, 'Overtime Hours': 350, 'Total Regular Pay': 65520, 'Total Overtime Pay': 16530 },
  { 'Employee ID': 'EMP-020', 'Job Title': 'Paramedic', 'FTE Count': 1.0, 'Avg Hourly Rate': 35.00, 'Regular Hours': 2080, 'Overtime Hours': 510, 'Total Regular Pay': 72800, 'Total Overtime Pay': 26770 },
  { 'Employee ID': 'EMP-021', 'Job Title': 'Paramedic', 'FTE Count': 1.0, 'Avg Hourly Rate': 46.00, 'Regular Hours': 2080, 'Overtime Hours': 200, 'Total Regular Pay': 95680, 'Total Overtime Pay': 13800 },
  { 'Employee ID': 'EMP-022', 'Job Title': 'Paramedic', 'FTE Count': 1.0, 'Avg Hourly Rate': 30.00, 'Regular Hours': 2080, 'Overtime Hours': 280, 'Total Regular Pay': 62400, 'Total Overtime Pay': 12600 },

  // Firefighter/EMT
  { 'Employee ID': 'EMP-023', 'Job Title': 'Firefighter/EMT', 'FTE Count': 1.0, 'Avg Hourly Rate': 25.00, 'Regular Hours': 2080, 'Overtime Hours': 240, 'Total Regular Pay': 52000, 'Total Overtime Pay': 9000 },
  { 'Employee ID': 'EMP-024', 'Job Title': 'Firefighter/EMT', 'FTE Count': 1.0, 'Avg Hourly Rate': 26.50, 'Regular Hours': 2080, 'Overtime Hours': 380, 'Total Regular Pay': 55120, 'Total Overtime Pay': 15100 },
  { 'Employee ID': 'EMP-025', 'Job Title': 'Firefighter/EMT', 'FTE Count': 1.0, 'Avg Hourly Rate': 27.00, 'Regular Hours': 2080, 'Overtime Hours': 450, 'Total Regular Pay': 56160, 'Total Overtime Pay': 18225 },
  { 'Employee ID': 'EMP-026', 'Job Title': 'Firefighter/EMT', 'FTE Count': 1.0, 'Avg Hourly Rate': 24.50, 'Regular Hours': 2080, 'Overtime Hours': 190, 'Total Regular Pay': 50960, 'Total Overtime Pay': 6980 },
  { 'Employee ID': 'EMP-027', 'Job Title': 'Firefighter/EMT', 'FTE Count': 1.0, 'Avg Hourly Rate': 26.00, 'Regular Hours': 2080, 'Overtime Hours': 310, 'Total Regular Pay': 54080, 'Total Overtime Pay': 12090 },
  { 'Employee ID': 'EMP-028', 'Job Title': 'Firefighter/EMT', 'FTE Count': 1.0, 'Avg Hourly Rate': 28.00, 'Regular Hours': 2080, 'Overtime Hours': 400, 'Total Regular Pay': 58240, 'Total Overtime Pay': 16800 },
  { 'Employee ID': 'EMP-029', 'Job Title': 'Firefighter/EMT', 'FTE Count': 1.0, 'Avg Hourly Rate': 25.50, 'Regular Hours': 2080, 'Overtime Hours': 220, 'Total Regular Pay': 53040, 'Total Overtime Pay': 8415 },

  // Captain/Shift Supervisor
  { 'Employee ID': 'EMP-030', 'Job Title': 'Captain/Shift Supervisor', 'FTE Count': 1.0, 'Avg Hourly Rate': 37.00, 'Regular Hours': 2080, 'Overtime Hours': 150, 'Total Regular Pay': 76960, 'Total Overtime Pay': 8325 },
  { 'Employee ID': 'EMP-031', 'Job Title': 'Captain/Shift Supervisor', 'FTE Count': 1.0, 'Avg Hourly Rate': 39.00, 'Regular Hours': 2080, 'Overtime Hours': 280, 'Total Regular Pay': 81120, 'Total Overtime Pay': 16380 },
  { 'Employee ID': 'EMP-032', 'Job Title': 'Captain/Shift Supervisor', 'FTE Count': 1.0, 'Avg Hourly Rate': 38.00, 'Regular Hours': 2080, 'Overtime Hours': 210, 'Total Regular Pay': 79040, 'Total Overtime Pay': 11970 },
  { 'Employee ID': 'EMP-033', 'Job Title': 'Captain/Shift Supervisor', 'FTE Count': 1.0, 'Avg Hourly Rate': 41.50, 'Regular Hours': 2080, 'Overtime Hours': 340, 'Total Regular Pay': 86320, 'Total Overtime Pay': 21160 },

  // Dispatcher
  { 'Employee ID': 'EMP-034', 'Job Title': 'Dispatcher', 'FTE Count': 1.0, 'Avg Hourly Rate': 20.00, 'Regular Hours': 2080, 'Overtime Hours': 120, 'Total Regular Pay': 41600, 'Total Overtime Pay': 3600 },
  { 'Employee ID': 'EMP-035', 'Job Title': 'Dispatcher', 'FTE Count': 1.0, 'Avg Hourly Rate': 21.50, 'Regular Hours': 2080, 'Overtime Hours': 280, 'Total Regular Pay': 44720, 'Total Overtime Pay': 9030 },
  { 'Employee ID': 'EMP-036', 'Job Title': 'Dispatcher', 'FTE Count': 1.0, 'Avg Hourly Rate': 22.50, 'Regular Hours': 2080, 'Overtime Hours': 190, 'Total Regular Pay': 46800, 'Total Overtime Pay': 6410 },
  { 'Employee ID': 'EMP-037', 'Job Title': 'Dispatcher', 'FTE Count': 1.0, 'Avg Hourly Rate': 19.50, 'Regular Hours': 2080, 'Overtime Hours': 80, 'Total Regular Pay': 40560, 'Total Overtime Pay': 2340 },
  { 'Employee ID': 'EMP-038', 'Job Title': 'Dispatcher', 'FTE Count': 1.0, 'Avg Hourly Rate': 21.00, 'Regular Hours': 2080, 'Overtime Hours': 220, 'Total Regular Pay': 43680, 'Total Overtime Pay': 6930 },

  // Fire Chief
  { 'Employee ID': 'EMP-039', 'Job Title': 'Fire Chief', 'FTE Count': 1.0, 'Avg Hourly Rate': 62.00, 'Regular Hours': 2080, 'Overtime Hours': 0, 'Total Regular Pay': 128960, 'Total Overtime Pay': 0 }
];

// 3. Emergency Room Arrival / CAD Data
const cadRows = [
  // 911 Emergency Medical
  { 'Incident ID': 'CAD-001', 'Call Source': '911 Emergency Medical', 'Disposition': 'Transported to ER', 'Dispatch Time (sec)': 42, 'Response Time (min)': 5.5, 'Scene Time (min)': 13.0, 'Transport Time (min)': 10.5 },
  { 'Incident ID': 'CAD-002', 'Call Source': '911 Emergency Medical', 'Disposition': 'Transported to ER', 'Dispatch Time (sec)': 48, 'Response Time (min)': 6.8, 'Scene Time (min)': 15.2, 'Transport Time (min)': 12.0 },
  { 'Incident ID': 'CAD-003', 'Call Source': '911 Emergency Medical', 'Disposition': 'Transported to ER', 'Dispatch Time (sec)': 35, 'Response Time (min)': 4.2, 'Scene Time (min)': 12.5, 'Transport Time (min)': 8.5 },
  { 'Incident ID': 'CAD-004', 'Call Source': '911 Emergency Medical', 'Disposition': 'Transported to ER', 'Dispatch Time (sec)': 55, 'Response Time (min)': 8.5, 'Scene Time (min)': 18.0, 'Transport Time (min)': 14.2 },
  { 'Incident ID': 'CAD-005', 'Call Source': '911 Emergency Medical', 'Disposition': 'Refusal of Care', 'Dispatch Time (sec)': 40, 'Response Time (min)': 6.0, 'Scene Time (min)': 14.0, 'Transport Time (min)': 0 },
  { 'Incident ID': 'CAD-006', 'Call Source': '911 Emergency Medical', 'Disposition': 'Transported to ER', 'Dispatch Time (sec)': 44, 'Response Time (min)': 5.8, 'Scene Time (min)': 14.8, 'Transport Time (min)': 11.0 },
  { 'Incident ID': 'CAD-007', 'Call Source': '911 Emergency Medical', 'Disposition': 'Transported to ER', 'Dispatch Time (sec)': 50, 'Response Time (min)': 7.2, 'Scene Time (min)': 16.5, 'Transport Time (min)': 11.5 },
  { 'Incident ID': 'CAD-008', 'Call Source': '911 Emergency Medical', 'Disposition': 'Transported to ER', 'Dispatch Time (sec)': 46, 'Response Time (min)': 6.4, 'Scene Time (min)': 13.8, 'Transport Time (min)': 12.5 },
  { 'Incident ID': 'CAD-009', 'Call Source': '911 Emergency Medical', 'Disposition': 'Transported to ER', 'Dispatch Time (sec)': 52, 'Response Time (min)': 14.2, 'Scene Time (min)': 15.0, 'Transport Time (min)': 13.0 },

  // 911 Non-Urgent Response
  { 'Incident ID': 'CAD-010', 'Call Source': '911 Non-Urgent Response', 'Disposition': 'Refusal of Care', 'Dispatch Time (sec)': 120, 'Response Time (min)': 13.5, 'Scene Time (min)': 10.5, 'Transport Time (min)': 0 },
  { 'Incident ID': 'CAD-011', 'Call Source': '911 Non-Urgent Response', 'Disposition': 'Refusal of Care', 'Dispatch Time (sec)': 110, 'Response Time (min)': 15.0, 'Scene Time (min)': 9.0, 'Transport Time (min)': 0 },
  { 'Incident ID': 'CAD-012', 'Call Source': '911 Non-Urgent Response', 'Disposition': 'Transported to ER', 'Dispatch Time (sec)': 130, 'Response Time (min)': 16.5, 'Scene Time (min)': 11.2, 'Transport Time (min)': 18.0 },
  { 'Incident ID': 'CAD-013', 'Call Source': '911 Non-Urgent Response', 'Disposition': 'Refusal of Care', 'Dispatch Time (sec)': 95, 'Response Time (min)': 12.0, 'Scene Time (min)': 8.5, 'Transport Time (min)': 0 },
  { 'Incident ID': 'CAD-014', 'Call Source': '911 Non-Urgent Response', 'Disposition': 'Refusal of Care', 'Dispatch Time (sec)': 105, 'Response Time (min)': 14.2, 'Scene Time (min)': 9.8, 'Transport Time (min)': 0 },
  { 'Incident ID': 'CAD-015', 'Call Source': '911 Non-Urgent Response', 'Disposition': 'Refusal of Care', 'Dispatch Time (sec)': 115, 'Response Time (min)': 15.8, 'Scene Time (min)': 10.0, 'Transport Time (min)': 0 },

  // Mutual Aid Request
  { 'Incident ID': 'CAD-016', 'Call Source': 'Mutual Aid Request', 'Disposition': 'Transferred to Partner', 'Dispatch Time (sec)': 85, 'Response Time (min)': 11.5, 'Scene Time (min)': 15.5, 'Transport Time (min)': 12.0 },
  { 'Incident ID': 'CAD-017', 'Call Source': 'Mutual Aid Request', 'Disposition': 'Transferred to Partner', 'Dispatch Time (sec)': 95, 'Response Time (min)': 13.0, 'Scene Time (min)': 16.8, 'Transport Time (min)': 14.0 },
  { 'Incident ID': 'CAD-018', 'Call Source': 'Mutual Aid Request', 'Disposition': 'Transferred to Partner', 'Dispatch Time (sec)': 90, 'Response Time (min)': 12.5, 'Scene Time (min)': 16.0, 'Transport Time (min)': 13.5 },
  { 'Incident ID': 'CAD-019', 'Call Source': 'Mutual Aid Request', 'Disposition': 'Transferred to Partner', 'Dispatch Time (sec)': 100, 'Response Time (min)': 14.0, 'Scene Time (min)': 17.5, 'Transport Time (min)': 15.0 },

  // Inter-Facility Transport
  { 'Incident ID': 'CAD-020', 'Call Source': 'Inter-Facility Transport', 'Disposition': 'Transported to ER', 'Dispatch Time (sec)': 180, 'Response Time (min)': 19.5, 'Scene Time (min)': 8.0, 'Transport Time (min)': 22.0 },
  { 'Incident ID': 'CAD-021', 'Call Source': 'Inter-Facility Transport', 'Disposition': 'Transported to ER', 'Dispatch Time (sec)': 170, 'Response Time (min)': 18.2, 'Scene Time (min)': 7.5, 'Transport Time (min)': 20.5 },
  { 'Incident ID': 'CAD-022', 'Call Source': 'Inter-Facility Transport', 'Disposition': 'Transported to ER', 'Dispatch Time (sec)': 160, 'Response Time (min)': 17.0, 'Scene Time (min)': 8.5, 'Transport Time (min)': 19.5 },
  { 'Incident ID': 'CAD-023', 'Call Source': 'Inter-Facility Transport', 'Disposition': 'Transported to ER', 'Dispatch Time (sec)': 190, 'Response Time (min)': 22.0, 'Scene Time (min)': 9.0, 'Transport Time (min)': 23.0 }
];

// Export pre-loaded workbooks matching the portal files
// 4. High-Variation Operations Dummy Data (100 rows for testing distributions)
const highVariationRows = [
  {
    "Employee ID": "EMP-117",
    "Month": "July 2024",
    "Job Title": "EMT-Basic",
    "Call Source": "Critical Care Transport",
    "FTE Count": 1.5,
    "Regular Hours": 273.4,
    "Overtime Hours": 0,
    "Total Regular Pay": 6231,
    "Total Overtime Pay": 0,
    "Run Volume": 232,
    "Avg Cost Per Transport": 2363,
    "Total Revenue": 474262,
    "PEMT Supplement": 162450,
    "Dispatch Time (sec)": 46,
    "Response Time (min)": 13.3,
    "Scene Time (min)": 40.7,
    "Transport Time (min)": 43.6
  },
  {
    "Employee ID": "EMP-108",
    "Month": "August 2024",
    "Job Title": "Dispatcher",
    "Call Source": "Disaster Response",
    "FTE Count": 1.2,
    "Regular Hours": 205.2,
    "Overtime Hours": 32.6,
    "Total Regular Pay": 3583,
    "Total Overtime Pay": 854,
    "Run Volume": 346,
    "Avg Cost Per Transport": 1575,
    "Total Revenue": 333071,
    "PEMT Supplement": 95788,
    "Dispatch Time (sec)": 90,
    "Response Time (min)": 21,
    "Scene Time (min)": 31.2,
    "Transport Time (min)": 11.9
  },
  {
    "Employee ID": "EMP-116",
    "Month": "August 2024",
    "Job Title": "Paramedic",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 0.5,
    "Regular Hours": 79.7,
    "Overtime Hours": 3,
    "Total Regular Pay": 2670,
    "Total Overtime Pay": 151,
    "Run Volume": 123,
    "Avg Cost Per Transport": 1113,
    "Total Revenue": 121637,
    "PEMT Supplement": 38847,
    "Dispatch Time (sec)": 50,
    "Response Time (min)": 10,
    "Scene Time (min)": 25.1,
    "Transport Time (min)": 19.2
  },
  {
    "Employee ID": "EMP-114",
    "Month": "September 2024",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Critical Care Transport",
    "FTE Count": 1,
    "Regular Hours": 171.1,
    "Overtime Hours": 0,
    "Total Regular Pay": 7219,
    "Total Overtime Pay": 0,
    "Run Volume": 37,
    "Avg Cost Per Transport": 1495,
    "Total Revenue": 38102,
    "PEMT Supplement": 8573,
    "Dispatch Time (sec)": 50,
    "Response Time (min)": 9.9,
    "Scene Time (min)": 18.6,
    "Transport Time (min)": 17.7
  },
  {
    "Employee ID": "EMP-110",
    "Month": "September 2024",
    "Job Title": "EMT-Basic",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 1.2,
    "Regular Hours": 189.9,
    "Overtime Hours": 0,
    "Total Regular Pay": 3812,
    "Total Overtime Pay": 0,
    "Run Volume": 168,
    "Avg Cost Per Transport": 269,
    "Total Revenue": 34779,
    "PEMT Supplement": 8470,
    "Dispatch Time (sec)": 173,
    "Response Time (min)": 29.6,
    "Scene Time (min)": 16.6,
    "Transport Time (min)": 35.4
  },
  {
    "Employee ID": "EMP-118",
    "Month": "September 2024",
    "Job Title": "EMT-Basic",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 0.8,
    "Regular Hours": 151.2,
    "Overtime Hours": 2.1,
    "Total Regular Pay": 2867,
    "Total Overtime Pay": 60,
    "Run Volume": 36,
    "Avg Cost Per Transport": 816,
    "Total Revenue": 20627,
    "PEMT Supplement": 5328,
    "Dispatch Time (sec)": 56,
    "Response Time (min)": 5.2,
    "Scene Time (min)": 14.9,
    "Transport Time (min)": 22.2
  },
  {
    "Employee ID": "EMP-114",
    "Month": "September 2024",
    "Job Title": "Firefighter/EMT",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 1.2,
    "Regular Hours": 213.1,
    "Overtime Hours": 23.3,
    "Total Regular Pay": 5485,
    "Total Overtime Pay": 900,
    "Run Volume": 172,
    "Avg Cost Per Transport": 969,
    "Total Revenue": 156125,
    "PEMT Supplement": 26028,
    "Dispatch Time (sec)": 59,
    "Response Time (min)": 8.3,
    "Scene Time (min)": 20,
    "Transport Time (min)": 32.8
  },
  {
    "Employee ID": "EMP-103",
    "Month": "September 2024",
    "Job Title": "Paramedic",
    "Call Source": "Critical Care Transport",
    "FTE Count": 1.2,
    "Regular Hours": 207.1,
    "Overtime Hours": 20.8,
    "Total Regular Pay": 6571,
    "Total Overtime Pay": 990,
    "Run Volume": 110,
    "Avg Cost Per Transport": 2467,
    "Total Revenue": 165112,
    "PEMT Supplement": 68287,
    "Dispatch Time (sec)": 59,
    "Response Time (min)": 18,
    "Scene Time (min)": 22.5,
    "Transport Time (min)": 39.3
  },
  {
    "Employee ID": "EMP-106",
    "Month": "October 2024",
    "Job Title": "Dispatcher",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 0.8,
    "Regular Hours": 129.1,
    "Overtime Hours": 0,
    "Total Regular Pay": 2482,
    "Total Overtime Pay": 0,
    "Run Volume": 115,
    "Avg Cost Per Transport": 935,
    "Total Revenue": 78048,
    "PEMT Supplement": 18598,
    "Dispatch Time (sec)": 33,
    "Response Time (min)": 5.6,
    "Scene Time (min)": 31.9,
    "Transport Time (min)": 9.4
  },
  {
    "Employee ID": "EMP-112",
    "Month": "October 2024",
    "Job Title": "Dispatcher",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 1.2,
    "Regular Hours": 218.3,
    "Overtime Hours": 19.6,
    "Total Regular Pay": 4272,
    "Total Overtime Pay": 575,
    "Run Volume": 167,
    "Avg Cost Per Transport": 495,
    "Total Revenue": 55465,
    "PEMT Supplement": 26670,
    "Dispatch Time (sec)": 69,
    "Response Time (min)": 13.7,
    "Scene Time (min)": 42.5,
    "Transport Time (min)": 13.6
  },
  {
    "Employee ID": "EMP-105",
    "Month": "October 2024",
    "Job Title": "EMT-Basic",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 1,
    "Regular Hours": 187.5,
    "Overtime Hours": 30.1,
    "Total Regular Pay": 4211,
    "Total Overtime Pay": 1014,
    "Run Volume": 132,
    "Avg Cost Per Transport": 922,
    "Total Revenue": 93239,
    "PEMT Supplement": 44295,
    "Dispatch Time (sec)": 78,
    "Response Time (min)": 14.4,
    "Scene Time (min)": 38.1,
    "Transport Time (min)": 24.7
  },
  {
    "Employee ID": "EMP-117",
    "Month": "November 2024",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Critical Care Transport",
    "FTE Count": 1.2,
    "Regular Hours": 212.7,
    "Overtime Hours": 33.3,
    "Total Regular Pay": 9833,
    "Total Overtime Pay": 2309,
    "Run Volume": 93,
    "Avg Cost Per Transport": 1348,
    "Total Revenue": 76180,
    "PEMT Supplement": 23859,
    "Dispatch Time (sec)": 59,
    "Response Time (min)": 13.8,
    "Scene Time (min)": 33.9,
    "Transport Time (min)": 30.8
  },
  {
    "Employee ID": "EMP-113",
    "Month": "November 2024",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Critical Care Transport",
    "FTE Count": 1,
    "Regular Hours": 168.2,
    "Overtime Hours": 43.1,
    "Total Regular Pay": 8847,
    "Total Overtime Pay": 3400,
    "Run Volume": 90,
    "Avg Cost Per Transport": 1497,
    "Total Revenue": 102726,
    "PEMT Supplement": 42633,
    "Dispatch Time (sec)": 41,
    "Response Time (min)": 9,
    "Scene Time (min)": 32.5,
    "Transport Time (min)": 9
  },
  {
    "Employee ID": "EMP-117",
    "Month": "November 2024",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Disaster Response",
    "FTE Count": 0.8,
    "Regular Hours": 148.9,
    "Overtime Hours": 41.8,
    "Total Regular Pay": 6213,
    "Total Overtime Pay": 2616,
    "Run Volume": 148,
    "Avg Cost Per Transport": 990,
    "Total Revenue": 117111,
    "PEMT Supplement": 44034,
    "Dispatch Time (sec)": 98,
    "Response Time (min)": 41.4,
    "Scene Time (min)": 46.7,
    "Transport Time (min)": 43.7
  },
  {
    "Employee ID": "EMP-113",
    "Month": "November 2024",
    "Job Title": "Paramedic",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 1.5,
    "Regular Hours": 277.2,
    "Overtime Hours": 33.1,
    "Total Regular Pay": 10749,
    "Total Overtime Pay": 1925,
    "Run Volume": 68,
    "Avg Cost Per Transport": 685,
    "Total Revenue": 33158,
    "PEMT Supplement": 11045,
    "Dispatch Time (sec)": 124,
    "Response Time (min)": 10.6,
    "Scene Time (min)": 17.2,
    "Transport Time (min)": 20.1
  },
  {
    "Employee ID": "EMP-112",
    "Month": "December 2024",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 1.5,
    "Regular Hours": 247.2,
    "Overtime Hours": 0,
    "Total Regular Pay": 12887,
    "Total Overtime Pay": 0,
    "Run Volume": 244,
    "Avg Cost Per Transport": 330,
    "Total Revenue": 51271,
    "PEMT Supplement": 15601,
    "Dispatch Time (sec)": 277,
    "Response Time (min)": 33.5,
    "Scene Time (min)": 38.8,
    "Transport Time (min)": 20.9
  },
  {
    "Employee ID": "EMP-118",
    "Month": "December 2024",
    "Job Title": "Dispatcher",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 0.5,
    "Regular Hours": 86.4,
    "Overtime Hours": 0,
    "Total Regular Pay": 1623,
    "Total Overtime Pay": 0,
    "Run Volume": 87,
    "Avg Cost Per Transport": 403,
    "Total Revenue": 24098,
    "PEMT Supplement": 9437,
    "Dispatch Time (sec)": 68,
    "Response Time (min)": 21.7,
    "Scene Time (min)": 40,
    "Transport Time (min)": 21.1
  },
  {
    "Employee ID": "EMP-118",
    "Month": "January 2025",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 2,
    "Regular Hours": 349.3,
    "Overtime Hours": 0,
    "Total Regular Pay": 16616,
    "Total Overtime Pay": 0,
    "Run Volume": 126,
    "Avg Cost Per Transport": 494,
    "Total Revenue": 56994,
    "PEMT Supplement": 24692,
    "Dispatch Time (sec)": 92,
    "Response Time (min)": 14.4,
    "Scene Time (min)": 19.6,
    "Transport Time (min)": 44.2
  },
  {
    "Employee ID": "EMP-106",
    "Month": "January 2025",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 0.5,
    "Regular Hours": 89.9,
    "Overtime Hours": 9.1,
    "Total Regular Pay": 4139,
    "Total Overtime Pay": 628,
    "Run Volume": 120,
    "Avg Cost Per Transport": 216,
    "Total Revenue": 19460,
    "PEMT Supplement": 5772,
    "Dispatch Time (sec)": 175,
    "Response Time (min)": 16.5,
    "Scene Time (min)": 37.6,
    "Transport Time (min)": 44.6
  },
  {
    "Employee ID": "EMP-104",
    "Month": "January 2025",
    "Job Title": "EMT-Basic",
    "Call Source": "Critical Care Transport",
    "FTE Count": 1.5,
    "Regular Hours": 248.7,
    "Overtime Hours": 40,
    "Total Regular Pay": 5391,
    "Total Overtime Pay": 1301,
    "Run Volume": 318,
    "Avg Cost Per Transport": 2320,
    "Total Revenue": 700310,
    "PEMT Supplement": 328467,
    "Dispatch Time (sec)": 34,
    "Response Time (min)": 8.2,
    "Scene Time (min)": 28,
    "Transport Time (min)": 12.4
  },
  {
    "Employee ID": "EMP-108",
    "Month": "January 2025",
    "Job Title": "Firefighter/EMT",
    "Call Source": "Disaster Response",
    "FTE Count": 1,
    "Regular Hours": 185,
    "Overtime Hours": 41.1,
    "Total Regular Pay": 5785,
    "Total Overtime Pay": 1928,
    "Run Volume": 60,
    "Avg Cost Per Transport": 942,
    "Total Revenue": 43052,
    "PEMT Supplement": 14504,
    "Dispatch Time (sec)": 91,
    "Response Time (min)": 26.7,
    "Scene Time (min)": 36.7,
    "Transport Time (min)": 22.5
  },
  {
    "Employee ID": "EMP-102",
    "Month": "January 2025",
    "Job Title": "Firefighter/EMT",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 1.2,
    "Regular Hours": 208.6,
    "Overtime Hours": 0.8,
    "Total Regular Pay": 5402,
    "Total Overtime Pay": 31,
    "Run Volume": 73,
    "Avg Cost Per Transport": 268,
    "Total Revenue": 14639,
    "PEMT Supplement": 3962,
    "Dispatch Time (sec)": 117,
    "Response Time (min)": 30.1,
    "Scene Time (min)": 35.3,
    "Transport Time (min)": 16.8
  },
  {
    "Employee ID": "EMP-116",
    "Month": "January 2025",
    "Job Title": "Paramedic",
    "Call Source": "Critical Care Transport",
    "FTE Count": 1,
    "Regular Hours": 165.5,
    "Overtime Hours": 46.8,
    "Total Regular Pay": 5833,
    "Total Overtime Pay": 2474,
    "Run Volume": 172,
    "Avg Cost Per Transport": 2360,
    "Total Revenue": 359666,
    "PEMT Supplement": 140941,
    "Dispatch Time (sec)": 35,
    "Response Time (min)": 15.6,
    "Scene Time (min)": 28.5,
    "Transport Time (min)": 12.9
  },
  {
    "Employee ID": "EMP-118",
    "Month": "January 2025",
    "Job Title": "Paramedic",
    "Call Source": "Critical Care Transport",
    "FTE Count": 0.8,
    "Regular Hours": 129.4,
    "Overtime Hours": 4.1,
    "Total Regular Pay": 5158,
    "Total Overtime Pay": 245,
    "Run Volume": 139,
    "Avg Cost Per Transport": 1394,
    "Total Revenue": 178484,
    "PEMT Supplement": 88205,
    "Dispatch Time (sec)": 48,
    "Response Time (min)": 15.4,
    "Scene Time (min)": 17.6,
    "Transport Time (min)": 30.6
  },
  {
    "Employee ID": "EMP-110",
    "Month": "February 2025",
    "Job Title": "Dispatcher",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 0.8,
    "Regular Hours": 144.1,
    "Overtime Hours": 12.6,
    "Total Regular Pay": 2786,
    "Total Overtime Pay": 365,
    "Run Volume": 86,
    "Avg Cost Per Transport": 515,
    "Total Revenue": 28761,
    "PEMT Supplement": 4780,
    "Dispatch Time (sec)": 112,
    "Response Time (min)": 15.1,
    "Scene Time (min)": 34.6,
    "Transport Time (min)": 32
  },
  {
    "Employee ID": "EMP-108",
    "Month": "February 2025",
    "Job Title": "Paramedic",
    "Call Source": "Disaster Response",
    "FTE Count": 0.5,
    "Regular Hours": 90.1,
    "Overtime Hours": 39,
    "Total Regular Pay": 2752,
    "Total Overtime Pay": 1787,
    "Run Volume": 32,
    "Avg Cost Per Transport": 928,
    "Total Revenue": 27961,
    "PEMT Supplement": 4351,
    "Dispatch Time (sec)": 38,
    "Response Time (min)": 31.7,
    "Scene Time (min)": 38.4,
    "Transport Time (min)": 8.7
  },
  {
    "Employee ID": "EMP-103",
    "Month": "February 2025",
    "Job Title": "Paramedic",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 1.2,
    "Regular Hours": 212.2,
    "Overtime Hours": 29.8,
    "Total Regular Pay": 7730,
    "Total Overtime Pay": 1628,
    "Run Volume": 184,
    "Avg Cost Per Transport": 471,
    "Total Revenue": 57008,
    "PEMT Supplement": 16953,
    "Dispatch Time (sec)": 157,
    "Response Time (min)": 22.4,
    "Scene Time (min)": 36.1,
    "Transport Time (min)": 46.6
  },
  {
    "Employee ID": "EMP-106",
    "Month": "March 2025",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 1,
    "Regular Hours": 187.2,
    "Overtime Hours": 0,
    "Total Regular Pay": 8536,
    "Total Overtime Pay": 0,
    "Run Volume": 145,
    "Avg Cost Per Transport": 558,
    "Total Revenue": 56320,
    "PEMT Supplement": 16359,
    "Dispatch Time (sec)": 130,
    "Response Time (min)": 20.9,
    "Scene Time (min)": 23.5,
    "Transport Time (min)": 52.2
  },
  {
    "Employee ID": "EMP-106",
    "Month": "March 2025",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Critical Care Transport",
    "FTE Count": 2,
    "Regular Hours": 317.7,
    "Overtime Hours": 34.6,
    "Total Regular Pay": 17001,
    "Total Overtime Pay": 2777,
    "Run Volume": 128,
    "Avg Cost Per Transport": 1840,
    "Total Revenue": 161055,
    "PEMT Supplement": 35290,
    "Dispatch Time (sec)": 40,
    "Response Time (min)": 12.8,
    "Scene Time (min)": 31,
    "Transport Time (min)": 47.4
  },
  {
    "Employee ID": "EMP-111",
    "Month": "March 2025",
    "Job Title": "EMT-Basic",
    "Call Source": "Disaster Response",
    "FTE Count": 1.2,
    "Regular Hours": 194,
    "Overtime Hours": 14.6,
    "Total Regular Pay": 4849,
    "Total Overtime Pay": 547,
    "Run Volume": 31,
    "Avg Cost Per Transport": 1580,
    "Total Revenue": 45807,
    "PEMT Supplement": 15592,
    "Dispatch Time (sec)": 50,
    "Response Time (min)": 40.3,
    "Scene Time (min)": 40.7,
    "Transport Time (min)": 44.2
  },
  {
    "Employee ID": "EMP-119",
    "Month": "March 2025",
    "Job Title": "Paramedic",
    "Call Source": "Disaster Response",
    "FTE Count": 0.8,
    "Regular Hours": 146.1,
    "Overtime Hours": 41.5,
    "Total Regular Pay": 5278,
    "Total Overtime Pay": 2249,
    "Run Volume": 47,
    "Avg Cost Per Transport": 1175,
    "Total Revenue": 40919,
    "PEMT Supplement": 11848,
    "Dispatch Time (sec)": 80,
    "Response Time (min)": 26,
    "Scene Time (min)": 33.6,
    "Transport Time (min)": 34
  },
  {
    "Employee ID": "EMP-111",
    "Month": "April 2025",
    "Job Title": "Dispatcher",
    "Call Source": "Critical Care Transport",
    "FTE Count": 1.2,
    "Regular Hours": 188.1,
    "Overtime Hours": 9.3,
    "Total Regular Pay": 4047,
    "Total Overtime Pay": 300,
    "Run Volume": 135,
    "Avg Cost Per Transport": 2260,
    "Total Revenue": 212392,
    "PEMT Supplement": 84733,
    "Dispatch Time (sec)": 49,
    "Response Time (min)": 15.7,
    "Scene Time (min)": 11.4,
    "Transport Time (min)": 34.3
  },
  {
    "Employee ID": "EMP-113",
    "Month": "April 2025",
    "Job Title": "EMT-Basic",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 1,
    "Regular Hours": 188.1,
    "Overtime Hours": 0.5,
    "Total Regular Pay": 4658,
    "Total Overtime Pay": 19,
    "Run Volume": 106,
    "Avg Cost Per Transport": 504,
    "Total Revenue": 35605,
    "PEMT Supplement": 14187,
    "Dispatch Time (sec)": 158,
    "Response Time (min)": 15.6,
    "Scene Time (min)": 16.1,
    "Transport Time (min)": 9.9
  },
  {
    "Employee ID": "EMP-106",
    "Month": "April 2025",
    "Job Title": "EMT-Basic",
    "Call Source": "Critical Care Transport",
    "FTE Count": 2,
    "Regular Hours": 337.3,
    "Overtime Hours": 41.9,
    "Total Regular Pay": 7756,
    "Total Overtime Pay": 1445,
    "Run Volume": 162,
    "Avg Cost Per Transport": 2234,
    "Total Revenue": 286058,
    "PEMT Supplement": 71396,
    "Dispatch Time (sec)": 59,
    "Response Time (min)": 19.1,
    "Scene Time (min)": 11.5,
    "Transport Time (min)": 8.6
  },
  {
    "Employee ID": "EMP-107",
    "Month": "April 2025",
    "Job Title": "Firefighter/EMT",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 2,
    "Regular Hours": 352.5,
    "Overtime Hours": 25.3,
    "Total Regular Pay": 9363,
    "Total Overtime Pay": 1008,
    "Run Volume": 277,
    "Avg Cost Per Transport": 562,
    "Total Revenue": 138770,
    "PEMT Supplement": 38152,
    "Dispatch Time (sec)": 167,
    "Response Time (min)": 13.8,
    "Scene Time (min)": 31.9,
    "Transport Time (min)": 50.6
  },
  {
    "Employee ID": "EMP-113",
    "Month": "April 2025",
    "Job Title": "Firefighter/EMT",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 0.8,
    "Regular Hours": 149.6,
    "Overtime Hours": 24.7,
    "Total Regular Pay": 3849,
    "Total Overtime Pay": 953,
    "Run Volume": 113,
    "Avg Cost Per Transport": 869,
    "Total Revenue": 67864,
    "PEMT Supplement": 24773,
    "Dispatch Time (sec)": 75,
    "Response Time (min)": 6.3,
    "Scene Time (min)": 41.4,
    "Transport Time (min)": 19.5
  },
  {
    "Employee ID": "EMP-110",
    "Month": "April 2025",
    "Job Title": "Firefighter/EMT",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 1.2,
    "Regular Hours": 217,
    "Overtime Hours": 31.8,
    "Total Regular Pay": 6794,
    "Total Overtime Pay": 1493,
    "Run Volume": 205,
    "Avg Cost Per Transport": 846,
    "Total Revenue": 150169,
    "PEMT Supplement": 62948,
    "Dispatch Time (sec)": 76,
    "Response Time (min)": 12.4,
    "Scene Time (min)": 39.5,
    "Transport Time (min)": 46.3
  },
  {
    "Employee ID": "EMP-120",
    "Month": "April 2025",
    "Job Title": "Paramedic",
    "Call Source": "Critical Care Transport",
    "FTE Count": 1.5,
    "Regular Hours": 244.5,
    "Overtime Hours": 0,
    "Total Regular Pay": 9040,
    "Total Overtime Pay": 0,
    "Run Volume": 129,
    "Avg Cost Per Transport": 2459,
    "Total Revenue": 264684,
    "PEMT Supplement": 125661,
    "Dispatch Time (sec)": 46,
    "Response Time (min)": 8.2,
    "Scene Time (min)": 42.3,
    "Transport Time (min)": 14
  },
  {
    "Employee ID": "EMP-111",
    "Month": "May 2025",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 2,
    "Regular Hours": 317.6,
    "Overtime Hours": 31,
    "Total Regular Pay": 16381,
    "Total Overtime Pay": 2398,
    "Run Volume": 112,
    "Avg Cost Per Transport": 772,
    "Total Revenue": 70028,
    "PEMT Supplement": 13555,
    "Dispatch Time (sec)": 33,
    "Response Time (min)": 8.1,
    "Scene Time (min)": 26.6,
    "Transport Time (min)": 49.8
  },
  {
    "Employee ID": "EMP-105",
    "Month": "May 2025",
    "Job Title": "EMT-Basic",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 0.8,
    "Regular Hours": 125,
    "Overtime Hours": 0,
    "Total Regular Pay": 3069,
    "Total Overtime Pay": 0,
    "Run Volume": 50,
    "Avg Cost Per Transport": 889,
    "Total Revenue": 37455,
    "PEMT Supplement": 6974,
    "Dispatch Time (sec)": 48,
    "Response Time (min)": 5.4,
    "Scene Time (min)": 21.3,
    "Transport Time (min)": 15.5
  },
  {
    "Employee ID": "EMP-114",
    "Month": "May 2025",
    "Job Title": "EMT-Basic",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 0.5,
    "Regular Hours": 82.8,
    "Overtime Hours": 12.3,
    "Total Regular Pay": 1952,
    "Total Overtime Pay": 435,
    "Run Volume": 26,
    "Avg Cost Per Transport": 248,
    "Total Revenue": 4981,
    "PEMT Supplement": 1514,
    "Dispatch Time (sec)": 101,
    "Response Time (min)": 30.2,
    "Scene Time (min)": 43.7,
    "Transport Time (min)": 16.7
  },
  {
    "Employee ID": "EMP-109",
    "Month": "May 2025",
    "Job Title": "Firefighter/EMT",
    "Call Source": "Disaster Response",
    "FTE Count": 2,
    "Regular Hours": 355.9,
    "Overtime Hours": 42.8,
    "Total Regular Pay": 9296,
    "Total Overtime Pay": 1677,
    "Run Volume": 178,
    "Avg Cost Per Transport": 1750,
    "Total Revenue": 207181,
    "PEMT Supplement": 85402,
    "Dispatch Time (sec)": 116,
    "Response Time (min)": 38.7,
    "Scene Time (min)": 11.6,
    "Transport Time (min)": 48.2
  },
  {
    "Employee ID": "EMP-105",
    "Month": "May 2025",
    "Job Title": "Firefighter/EMT",
    "Call Source": "Disaster Response",
    "FTE Count": 1,
    "Regular Hours": 184.5,
    "Overtime Hours": 44.3,
    "Total Regular Pay": 4526,
    "Total Overtime Pay": 1630,
    "Run Volume": 156,
    "Avg Cost Per Transport": 1571,
    "Total Revenue": 208677,
    "PEMT Supplement": 55684,
    "Dispatch Time (sec)": 60,
    "Response Time (min)": 44.4,
    "Scene Time (min)": 11.6,
    "Transport Time (min)": 33.4
  },
  {
    "Employee ID": "EMP-102",
    "Month": "May 2025",
    "Job Title": "Paramedic",
    "Call Source": "Disaster Response",
    "FTE Count": 1.5,
    "Regular Hours": 253.2,
    "Overtime Hours": 15.4,
    "Total Regular Pay": 9306,
    "Total Overtime Pay": 849,
    "Run Volume": 64,
    "Avg Cost Per Transport": 1375,
    "Total Revenue": 62456,
    "PEMT Supplement": 25871,
    "Dispatch Time (sec)": 114,
    "Response Time (min)": 24.6,
    "Scene Time (min)": 38.9,
    "Transport Time (min)": 42
  },
  {
    "Employee ID": "EMP-106",
    "Month": "June 2025",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 1,
    "Regular Hours": 158.3,
    "Overtime Hours": 8.2,
    "Total Regular Pay": 8278,
    "Total Overtime Pay": 643,
    "Run Volume": 110,
    "Avg Cost Per Transport": 648,
    "Total Revenue": 62368,
    "PEMT Supplement": 29157,
    "Dispatch Time (sec)": 158,
    "Response Time (min)": 20.2,
    "Scene Time (min)": 48.6,
    "Transport Time (min)": 30.9
  },
  {
    "Employee ID": "EMP-104",
    "Month": "June 2025",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 2,
    "Regular Hours": 319.5,
    "Overtime Hours": 0,
    "Total Regular Pay": 15119,
    "Total Overtime Pay": 0,
    "Run Volume": 214,
    "Avg Cost Per Transport": 212,
    "Total Revenue": 32091,
    "PEMT Supplement": 11925,
    "Dispatch Time (sec)": 271,
    "Response Time (min)": 32.5,
    "Scene Time (min)": 27.6,
    "Transport Time (min)": 35.5
  },
  {
    "Employee ID": "EMP-120",
    "Month": "June 2025",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 0.5,
    "Regular Hours": 78.4,
    "Overtime Hours": 0.6,
    "Total Regular Pay": 3460,
    "Total Overtime Pay": 40,
    "Run Volume": 22,
    "Avg Cost Per Transport": 423,
    "Total Revenue": 7651,
    "PEMT Supplement": 3019,
    "Dispatch Time (sec)": 178,
    "Response Time (min)": 12.4,
    "Scene Time (min)": 49.6,
    "Transport Time (min)": 17.4
  },
  {
    "Employee ID": "EMP-106",
    "Month": "June 2025",
    "Job Title": "EMT-Basic",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 1.2,
    "Regular Hours": 227.7,
    "Overtime Hours": 0,
    "Total Regular Pay": 5678,
    "Total Overtime Pay": 0,
    "Run Volume": 175,
    "Avg Cost Per Transport": 624,
    "Total Revenue": 96066,
    "PEMT Supplement": 18304,
    "Dispatch Time (sec)": 129,
    "Response Time (min)": 21.8,
    "Scene Time (min)": 40.9,
    "Transport Time (min)": 30.5
  },
  {
    "Employee ID": "EMP-101",
    "Month": "June 2025",
    "Job Title": "Paramedic",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 1.5,
    "Regular Hours": 250.2,
    "Overtime Hours": 16.4,
    "Total Regular Pay": 8478,
    "Total Overtime Pay": 834,
    "Run Volume": 177,
    "Avg Cost Per Transport": 155,
    "Total Revenue": 18149,
    "PEMT Supplement": 8964,
    "Dispatch Time (sec)": 153,
    "Response Time (min)": 18.3,
    "Scene Time (min)": 33.8,
    "Transport Time (min)": 20.8
  },
  {
    "Employee ID": "EMP-119",
    "Month": "June 2025",
    "Job Title": "Paramedic",
    "Call Source": "Disaster Response",
    "FTE Count": 1.5,
    "Regular Hours": 265.5,
    "Overtime Hours": 38.9,
    "Total Regular Pay": 9106,
    "Total Overtime Pay": 2001,
    "Run Volume": 214,
    "Avg Cost Per Transport": 1753,
    "Total Revenue": 301553,
    "PEMT Supplement": 98644,
    "Dispatch Time (sec)": 77,
    "Response Time (min)": 20.9,
    "Scene Time (min)": 18.3,
    "Transport Time (min)": 24.6
  },
  {
    "Employee ID": "EMP-104",
    "Month": "July 2025",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 1.5,
    "Regular Hours": 237.4,
    "Overtime Hours": 11,
    "Total Regular Pay": 12988,
    "Total Overtime Pay": 903,
    "Run Volume": 63,
    "Avg Cost Per Transport": 813,
    "Total Revenue": 36171,
    "PEMT Supplement": 5502,
    "Dispatch Time (sec)": 68,
    "Response Time (min)": 9.4,
    "Scene Time (min)": 15,
    "Transport Time (min)": 31.8
  },
  {
    "Employee ID": "EMP-105",
    "Month": "July 2025",
    "Job Title": "Dispatcher",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 1,
    "Regular Hours": 185.2,
    "Overtime Hours": 48.9,
    "Total Regular Pay": 4142,
    "Total Overtime Pay": 1641,
    "Run Volume": 56,
    "Avg Cost Per Transport": 218,
    "Total Revenue": 10000,
    "PEMT Supplement": 4742,
    "Dispatch Time (sec)": 193,
    "Response Time (min)": 33.7,
    "Scene Time (min)": 19.3,
    "Transport Time (min)": 50.7
  },
  {
    "Employee ID": "EMP-107",
    "Month": "July 2025",
    "Job Title": "Firefighter/EMT",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 1.2,
    "Regular Hours": 227,
    "Overtime Hours": 20.4,
    "Total Regular Pay": 6154,
    "Total Overtime Pay": 830,
    "Run Volume": 195,
    "Avg Cost Per Transport": 657,
    "Total Revenue": 93157,
    "PEMT Supplement": 32589,
    "Dispatch Time (sec)": 169,
    "Response Time (min)": 23.3,
    "Scene Time (min)": 18.7,
    "Transport Time (min)": 39.9
  },
  {
    "Employee ID": "EMP-104",
    "Month": "July 2025",
    "Job Title": "Firefighter/EMT",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 2,
    "Regular Hours": 328.5,
    "Overtime Hours": 0,
    "Total Regular Pay": 10561,
    "Total Overtime Pay": 0,
    "Run Volume": 251,
    "Avg Cost Per Transport": 285,
    "Total Revenue": 58456,
    "PEMT Supplement": 9676,
    "Dispatch Time (sec)": 218,
    "Response Time (min)": 23.7,
    "Scene Time (min)": 33.2,
    "Transport Time (min)": 9.9
  },
  {
    "Employee ID": "EMP-110",
    "Month": "July 2025",
    "Job Title": "Paramedic",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 0.8,
    "Regular Hours": 138.5,
    "Overtime Hours": 40.1,
    "Total Regular Pay": 5508,
    "Total Overtime Pay": 2392,
    "Run Volume": 53,
    "Avg Cost Per Transport": 677,
    "Total Revenue": 29925,
    "PEMT Supplement": 5858,
    "Dispatch Time (sec)": 105,
    "Response Time (min)": 19.4,
    "Scene Time (min)": 47.1,
    "Transport Time (min)": 19.1
  },
  {
    "Employee ID": "EMP-120",
    "Month": "August 2025",
    "Job Title": "EMT-Basic",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 0.5,
    "Regular Hours": 91.1,
    "Overtime Hours": 0,
    "Total Regular Pay": 2107,
    "Total Overtime Pay": 0,
    "Run Volume": 122,
    "Avg Cost Per Transport": 1121,
    "Total Revenue": 107883,
    "PEMT Supplement": 30157,
    "Dispatch Time (sec)": 64,
    "Response Time (min)": 10.9,
    "Scene Time (min)": 10.5,
    "Transport Time (min)": 20.4
  },
  {
    "Employee ID": "EMP-108",
    "Month": "August 2025",
    "Job Title": "EMT-Basic",
    "Call Source": "Disaster Response",
    "FTE Count": 1.2,
    "Regular Hours": 221.7,
    "Overtime Hours": 0,
    "Total Regular Pay": 4277,
    "Total Overtime Pay": 0,
    "Run Volume": 95,
    "Avg Cost Per Transport": 1455,
    "Total Revenue": 82979,
    "PEMT Supplement": 20859,
    "Dispatch Time (sec)": 69,
    "Response Time (min)": 28.9,
    "Scene Time (min)": 15.3,
    "Transport Time (min)": 31.3
  },
  {
    "Employee ID": "EMP-103",
    "Month": "August 2025",
    "Job Title": "Paramedic",
    "Call Source": "Disaster Response",
    "FTE Count": 0.5,
    "Regular Hours": 93.3,
    "Overtime Hours": 1.4,
    "Total Regular Pay": 3040,
    "Total Overtime Pay": 68,
    "Run Volume": 130,
    "Avg Cost Per Transport": 1233,
    "Total Revenue": 127363,
    "PEMT Supplement": 56752,
    "Dispatch Time (sec)": 112,
    "Response Time (min)": 25,
    "Scene Time (min)": 35.8,
    "Transport Time (min)": 36.6
  },
  {
    "Employee ID": "EMP-103",
    "Month": "September 2025",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Critical Care Transport",
    "FTE Count": 0.8,
    "Regular Hours": 126.2,
    "Overtime Hours": 45.5,
    "Total Regular Pay": 6136,
    "Total Overtime Pay": 3318,
    "Run Volume": 115,
    "Avg Cost Per Transport": 2218,
    "Total Revenue": 195591,
    "PEMT Supplement": 77023,
    "Dispatch Time (sec)": 30,
    "Response Time (min)": 11.9,
    "Scene Time (min)": 41.2,
    "Transport Time (min)": 27.2
  },
  {
    "Employee ID": "EMP-112",
    "Month": "September 2025",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 0.8,
    "Regular Hours": 127.7,
    "Overtime Hours": 30.5,
    "Total Regular Pay": 5559,
    "Total Overtime Pay": 1992,
    "Run Volume": 59,
    "Avg Cost Per Transport": 555,
    "Total Revenue": 23477,
    "PEMT Supplement": 9031,
    "Dispatch Time (sec)": 127,
    "Response Time (min)": 20.4,
    "Scene Time (min)": 38.9,
    "Transport Time (min)": 46.2
  },
  {
    "Employee ID": "EMP-108",
    "Month": "September 2025",
    "Job Title": "Dispatcher",
    "Call Source": "Critical Care Transport",
    "FTE Count": 0.5,
    "Regular Hours": 94.5,
    "Overtime Hours": 28.4,
    "Total Regular Pay": 1818,
    "Total Overtime Pay": 820,
    "Run Volume": 41,
    "Avg Cost Per Transport": 2287,
    "Total Revenue": 69261,
    "PEMT Supplement": 11401,
    "Dispatch Time (sec)": 21,
    "Response Time (min)": 18.7,
    "Scene Time (min)": 46.4,
    "Transport Time (min)": 9.4
  },
  {
    "Employee ID": "EMP-102",
    "Month": "September 2025",
    "Job Title": "EMT-Basic",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 2,
    "Regular Hours": 375.8,
    "Overtime Hours": 44.9,
    "Total Regular Pay": 8387,
    "Total Overtime Pay": 1503,
    "Run Volume": 171,
    "Avg Cost Per Transport": 256,
    "Total Revenue": 33908,
    "PEMT Supplement": 14313,
    "Dispatch Time (sec)": 300,
    "Response Time (min)": 34.4,
    "Scene Time (min)": 32.5,
    "Transport Time (min)": 27.5
  },
  {
    "Employee ID": "EMP-108",
    "Month": "September 2025",
    "Job Title": "EMT-Basic",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 1.2,
    "Regular Hours": 187.3,
    "Overtime Hours": 20,
    "Total Regular Pay": 3578,
    "Total Overtime Pay": 573,
    "Run Volume": 135,
    "Avg Cost Per Transport": 680,
    "Total Revenue": 80872,
    "PEMT Supplement": 29464,
    "Dispatch Time (sec)": 140,
    "Response Time (min)": 18.8,
    "Scene Time (min)": 38.8,
    "Transport Time (min)": 29.4
  },
  {
    "Employee ID": "EMP-110",
    "Month": "September 2025",
    "Job Title": "Paramedic",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 0.5,
    "Regular Hours": 80.6,
    "Overtime Hours": 36.2,
    "Total Regular Pay": 2689,
    "Total Overtime Pay": 1811,
    "Run Volume": 33,
    "Avg Cost Per Transport": 434,
    "Total Revenue": 8742,
    "PEMT Supplement": 1623,
    "Dispatch Time (sec)": 168,
    "Response Time (min)": 12.2,
    "Scene Time (min)": 10.4,
    "Transport Time (min)": 17.2
  },
  {
    "Employee ID": "EMP-106",
    "Month": "October 2025",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 1,
    "Regular Hours": 188,
    "Overtime Hours": 11.2,
    "Total Regular Pay": 9155,
    "Total Overtime Pay": 818,
    "Run Volume": 174,
    "Avg Cost Per Transport": 206,
    "Total Revenue": 32289,
    "PEMT Supplement": 6894,
    "Dispatch Time (sec)": 221,
    "Response Time (min)": 20.7,
    "Scene Time (min)": 47.9,
    "Transport Time (min)": 29.2
  },
  {
    "Employee ID": "EMP-115",
    "Month": "October 2025",
    "Job Title": "Dispatcher",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 1.2,
    "Regular Hours": 216,
    "Overtime Hours": 38.9,
    "Total Regular Pay": 4627,
    "Total Overtime Pay": 1250,
    "Run Volume": 116,
    "Avg Cost Per Transport": 340,
    "Total Revenue": 34850,
    "PEMT Supplement": 11491,
    "Dispatch Time (sec)": 164,
    "Response Time (min)": 21.2,
    "Scene Time (min)": 35,
    "Transport Time (min)": 23.8
  },
  {
    "Employee ID": "EMP-110",
    "Month": "October 2025",
    "Job Title": "Paramedic",
    "Call Source": "Disaster Response",
    "FTE Count": 0.8,
    "Regular Hours": 132.6,
    "Overtime Hours": 23.8,
    "Total Regular Pay": 5146,
    "Total Overtime Pay": 1385,
    "Run Volume": 35,
    "Avg Cost Per Transport": 1365,
    "Total Revenue": 36939,
    "PEMT Supplement": 8740,
    "Dispatch Time (sec)": 91,
    "Response Time (min)": 43.5,
    "Scene Time (min)": 27.1,
    "Transport Time (min)": 20
  },
  {
    "Employee ID": "EMP-109",
    "Month": "October 2025",
    "Job Title": "Paramedic",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 1,
    "Regular Hours": 184.5,
    "Overtime Hours": 46.6,
    "Total Regular Pay": 6878,
    "Total Overtime Pay": 2606,
    "Run Volume": 92,
    "Avg Cost Per Transport": 743,
    "Total Revenue": 41019,
    "PEMT Supplement": 9099,
    "Dispatch Time (sec)": 74,
    "Response Time (min)": 9.7,
    "Scene Time (min)": 14,
    "Transport Time (min)": 10.9
  },
  {
    "Employee ID": "EMP-112",
    "Month": "November 2025",
    "Job Title": "Dispatcher",
    "Call Source": "Disaster Response",
    "FTE Count": 0.8,
    "Regular Hours": 145.6,
    "Overtime Hours": 2.3,
    "Total Regular Pay": 3279,
    "Total Overtime Pay": 78,
    "Run Volume": 67,
    "Avg Cost Per Transport": 1181,
    "Total Revenue": 66763,
    "PEMT Supplement": 32741,
    "Dispatch Time (sec)": 93,
    "Response Time (min)": 24.1,
    "Scene Time (min)": 18.7,
    "Transport Time (min)": 26.9
  },
  {
    "Employee ID": "EMP-102",
    "Month": "November 2025",
    "Job Title": "Paramedic",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 1.2,
    "Regular Hours": 220.1,
    "Overtime Hours": 14.4,
    "Total Regular Pay": 6655,
    "Total Overtime Pay": 653,
    "Run Volume": 91,
    "Avg Cost Per Transport": 847,
    "Total Revenue": 70742,
    "PEMT Supplement": 28172,
    "Dispatch Time (sec)": 76,
    "Response Time (min)": 13,
    "Scene Time (min)": 39.2,
    "Transport Time (min)": 18.1
  },
  {
    "Employee ID": "EMP-105",
    "Month": "December 2025",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 0.8,
    "Regular Hours": 125.4,
    "Overtime Hours": 46.1,
    "Total Regular Pay": 6746,
    "Total Overtime Pay": 3720,
    "Run Volume": 152,
    "Avg Cost Per Transport": 491,
    "Total Revenue": 66806,
    "PEMT Supplement": 15091,
    "Dispatch Time (sec)": 168,
    "Response Time (min)": 14.3,
    "Scene Time (min)": 44,
    "Transport Time (min)": 50
  },
  {
    "Employee ID": "EMP-102",
    "Month": "December 2025",
    "Job Title": "Dispatcher",
    "Call Source": "Critical Care Transport",
    "FTE Count": 2,
    "Regular Hours": 334.3,
    "Overtime Hours": 16.4,
    "Total Regular Pay": 6114,
    "Total Overtime Pay": 450,
    "Run Volume": 195,
    "Avg Cost Per Transport": 2310,
    "Total Revenue": 376384,
    "PEMT Supplement": 174916,
    "Dispatch Time (sec)": 56,
    "Response Time (min)": 16.2,
    "Scene Time (min)": 28.4,
    "Transport Time (min)": 13.6
  },
  {
    "Employee ID": "EMP-109",
    "Month": "December 2025",
    "Job Title": "Dispatcher",
    "Call Source": "Disaster Response",
    "FTE Count": 1,
    "Regular Hours": 181.8,
    "Overtime Hours": 11.4,
    "Total Regular Pay": 4021,
    "Total Overtime Pay": 378,
    "Run Volume": 132,
    "Avg Cost Per Transport": 1410,
    "Total Revenue": 154510,
    "PEMT Supplement": 59616,
    "Dispatch Time (sec)": 45,
    "Response Time (min)": 41.5,
    "Scene Time (min)": 20,
    "Transport Time (min)": 44.8
  },
  {
    "Employee ID": "EMP-107",
    "Month": "January 2026",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 1,
    "Regular Hours": 159.6,
    "Overtime Hours": 27,
    "Total Regular Pay": 7350,
    "Total Overtime Pay": 1865,
    "Run Volume": 241,
    "Avg Cost Per Transport": 775,
    "Total Revenue": 127797,
    "PEMT Supplement": 61188,
    "Dispatch Time (sec)": 87,
    "Response Time (min)": 8.3,
    "Scene Time (min)": 36.5,
    "Transport Time (min)": 14.4
  },
  {
    "Employee ID": "EMP-103",
    "Month": "January 2026",
    "Job Title": "EMT-Basic",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 2,
    "Regular Hours": 326.2,
    "Overtime Hours": 31.1,
    "Total Regular Pay": 6378,
    "Total Overtime Pay": 912,
    "Run Volume": 428,
    "Avg Cost Per Transport": 990,
    "Total Revenue": 292007,
    "PEMT Supplement": 142820,
    "Dispatch Time (sec)": 66,
    "Response Time (min)": 8.5,
    "Scene Time (min)": 35.5,
    "Transport Time (min)": 49.8
  },
  {
    "Employee ID": "EMP-113",
    "Month": "January 2026",
    "Job Title": "EMT-Basic",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 1.5,
    "Regular Hours": 241.5,
    "Overtime Hours": 33.3,
    "Total Regular Pay": 4529,
    "Total Overtime Pay": 937,
    "Run Volume": 213,
    "Avg Cost Per Transport": 181,
    "Total Revenue": 33341,
    "PEMT Supplement": 6691,
    "Dispatch Time (sec)": 118,
    "Response Time (min)": 33.5,
    "Scene Time (min)": 20.9,
    "Transport Time (min)": 32
  },
  {
    "Employee ID": "EMP-104",
    "Month": "January 2026",
    "Job Title": "Firefighter/EMT",
    "Call Source": "Critical Care Transport",
    "FTE Count": 1.5,
    "Regular Hours": 256.7,
    "Overtime Hours": 53.3,
    "Total Regular Pay": 7362,
    "Total Overtime Pay": 2293,
    "Run Volume": 174,
    "Avg Cost Per Transport": 1561,
    "Total Revenue": 240927,
    "PEMT Supplement": 38458,
    "Dispatch Time (sec)": 60,
    "Response Time (min)": 16.3,
    "Scene Time (min)": 16.9,
    "Transport Time (min)": 22.8
  },
  {
    "Employee ID": "EMP-109",
    "Month": "February 2026",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 0.8,
    "Regular Hours": 148.1,
    "Overtime Hours": 1.1,
    "Total Regular Pay": 6347,
    "Total Overtime Pay": 71,
    "Run Volume": 23,
    "Avg Cost Per Transport": 730,
    "Total Revenue": 15380,
    "PEMT Supplement": 4812,
    "Dispatch Time (sec)": 43,
    "Response Time (min)": 6.7,
    "Scene Time (min)": 44,
    "Transport Time (min)": 15.1
  },
  {
    "Employee ID": "EMP-103",
    "Month": "February 2026",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 0.5,
    "Regular Hours": 89.1,
    "Overtime Hours": 0,
    "Total Regular Pay": 4562,
    "Total Overtime Pay": 0,
    "Run Volume": 14,
    "Avg Cost Per Transport": 201,
    "Total Revenue": 1963,
    "PEMT Supplement": 838,
    "Dispatch Time (sec)": 123,
    "Response Time (min)": 34.7,
    "Scene Time (min)": 40.2,
    "Transport Time (min)": 28.4
  },
  {
    "Employee ID": "EMP-118",
    "Month": "February 2026",
    "Job Title": "Dispatcher",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 0.8,
    "Regular Hours": 148.9,
    "Overtime Hours": 0,
    "Total Regular Pay": 2894,
    "Total Overtime Pay": 0,
    "Run Volume": 56,
    "Avg Cost Per Transport": 201,
    "Total Revenue": 6952,
    "PEMT Supplement": 2665,
    "Dispatch Time (sec)": 213,
    "Response Time (min)": 31.5,
    "Scene Time (min)": 32.2,
    "Transport Time (min)": 16
  },
  {
    "Employee ID": "EMP-102",
    "Month": "February 2026",
    "Job Title": "EMT-Basic",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 0.8,
    "Regular Hours": 151.1,
    "Overtime Hours": 35.7,
    "Total Regular Pay": 3542,
    "Total Overtime Pay": 1255,
    "Run Volume": 42,
    "Avg Cost Per Transport": 524,
    "Total Revenue": 14091,
    "PEMT Supplement": 2718,
    "Dispatch Time (sec)": 119,
    "Response Time (min)": 12.9,
    "Scene Time (min)": 16.1,
    "Transport Time (min)": 23.8
  },
  {
    "Employee ID": "EMP-108",
    "Month": "February 2026",
    "Job Title": "Firefighter/EMT",
    "Call Source": "Disaster Response",
    "FTE Count": 0.8,
    "Regular Hours": 126.8,
    "Overtime Hours": 0,
    "Total Regular Pay": 3927,
    "Total Overtime Pay": 0,
    "Run Volume": 70,
    "Avg Cost Per Transport": 1667,
    "Total Revenue": 91511,
    "PEMT Supplement": 28918,
    "Dispatch Time (sec)": 65,
    "Response Time (min)": 16.6,
    "Scene Time (min)": 43.8,
    "Transport Time (min)": 43.9
  },
  {
    "Employee ID": "EMP-104",
    "Month": "February 2026",
    "Job Title": "Firefighter/EMT",
    "Call Source": "Critical Care Transport",
    "FTE Count": 1.2,
    "Regular Hours": 218.2,
    "Overtime Hours": 44.2,
    "Total Regular Pay": 5861,
    "Total Overtime Pay": 1781,
    "Run Volume": 188,
    "Avg Cost Per Transport": 1489,
    "Total Revenue": 204522,
    "PEMT Supplement": 74931,
    "Dispatch Time (sec)": 57,
    "Response Time (min)": 17.9,
    "Scene Time (min)": 18.5,
    "Transport Time (min)": 20.7
  },
  {
    "Employee ID": "EMP-110",
    "Month": "February 2026",
    "Job Title": "Paramedic",
    "Call Source": "Disaster Response",
    "FTE Count": 1.2,
    "Regular Hours": 223.3,
    "Overtime Hours": 0,
    "Total Regular Pay": 7222,
    "Total Overtime Pay": 0,
    "Run Volume": 128,
    "Avg Cost Per Transport": 1453,
    "Total Revenue": 165732,
    "PEMT Supplement": 71571,
    "Dispatch Time (sec)": 114,
    "Response Time (min)": 21.9,
    "Scene Time (min)": 34.3,
    "Transport Time (min)": 51.6
  },
  {
    "Employee ID": "EMP-119",
    "Month": "March 2026",
    "Job Title": "Dispatcher",
    "Call Source": "Critical Care Transport",
    "FTE Count": 1.2,
    "Regular Hours": 201,
    "Overtime Hours": 37.3,
    "Total Regular Pay": 4589,
    "Total Overtime Pay": 1277,
    "Run Volume": 74,
    "Avg Cost Per Transport": 2380,
    "Total Revenue": 128127,
    "PEMT Supplement": 45347,
    "Dispatch Time (sec)": 35,
    "Response Time (min)": 14.1,
    "Scene Time (min)": 16.3,
    "Transport Time (min)": 18.1
  },
  {
    "Employee ID": "EMP-112",
    "Month": "March 2026",
    "Job Title": "Firefighter/EMT",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 2,
    "Regular Hours": 374.8,
    "Overtime Hours": 45.1,
    "Total Regular Pay": 11054,
    "Total Overtime Pay": 1995,
    "Run Volume": 98,
    "Avg Cost Per Transport": 638,
    "Total Revenue": 54196,
    "PEMT Supplement": 17771,
    "Dispatch Time (sec)": 135,
    "Response Time (min)": 18.9,
    "Scene Time (min)": 35.5,
    "Transport Time (min)": 8.8
  },
  {
    "Employee ID": "EMP-114",
    "Month": "April 2026",
    "Job Title": "EMT-Basic",
    "Call Source": "Disaster Response",
    "FTE Count": 0.8,
    "Regular Hours": 150.7,
    "Overtime Hours": 0,
    "Total Regular Pay": 3308,
    "Total Overtime Pay": 0,
    "Run Volume": 99,
    "Avg Cost Per Transport": 1285,
    "Total Revenue": 110565,
    "PEMT Supplement": 25613,
    "Dispatch Time (sec)": 53,
    "Response Time (min)": 41.9,
    "Scene Time (min)": 46.5,
    "Transport Time (min)": 39
  },
  {
    "Employee ID": "EMP-114",
    "Month": "April 2026",
    "Job Title": "EMT-Basic",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 0.5,
    "Regular Hours": 83,
    "Overtime Hours": 4,
    "Total Regular Pay": 1598,
    "Total Overtime Pay": 115,
    "Run Volume": 21,
    "Avg Cost Per Transport": 162,
    "Total Revenue": 2208,
    "PEMT Supplement": 386,
    "Dispatch Time (sec)": 146,
    "Response Time (min)": 34,
    "Scene Time (min)": 41.4,
    "Transport Time (min)": 8.3
  },
  {
    "Employee ID": "EMP-105",
    "Month": "April 2026",
    "Job Title": "Paramedic",
    "Call Source": "Disaster Response",
    "FTE Count": 1,
    "Regular Hours": 164.1,
    "Overtime Hours": 53.8,
    "Total Regular Pay": 6604,
    "Total Overtime Pay": 3248,
    "Run Volume": 63,
    "Avg Cost Per Transport": 1737,
    "Total Revenue": 68900,
    "PEMT Supplement": 24418,
    "Dispatch Time (sec)": 106,
    "Response Time (min)": 36.9,
    "Scene Time (min)": 49.3,
    "Transport Time (min)": 40.4
  },
  {
    "Employee ID": "EMP-115",
    "Month": "May 2026",
    "Job Title": "EMT-Basic",
    "Call Source": "Disaster Response",
    "FTE Count": 2,
    "Regular Hours": 322.8,
    "Overtime Hours": 0,
    "Total Regular Pay": 7822,
    "Total Overtime Pay": 0,
    "Run Volume": 183,
    "Avg Cost Per Transport": 1291,
    "Total Revenue": 155251,
    "PEMT Supplement": 35530,
    "Dispatch Time (sec)": 17,
    "Response Time (min)": 44.9,
    "Scene Time (min)": 17.1,
    "Transport Time (min)": 31.8
  },
  {
    "Employee ID": "EMP-106",
    "Month": "May 2026",
    "Job Title": "EMT-Basic",
    "Call Source": "Critical Care Transport",
    "FTE Count": 1.2,
    "Regular Hours": 203.3,
    "Overtime Hours": 44.5,
    "Total Regular Pay": 5099,
    "Total Overtime Pay": 1674,
    "Run Volume": 93,
    "Avg Cost Per Transport": 1693,
    "Total Revenue": 107368,
    "PEMT Supplement": 27829,
    "Dispatch Time (sec)": 54,
    "Response Time (min)": 18.5,
    "Scene Time (min)": 44.4,
    "Transport Time (min)": 42.5
  },
  {
    "Employee ID": "EMP-112",
    "Month": "May 2026",
    "Job Title": "Firefighter/EMT",
    "Call Source": "Disaster Response",
    "FTE Count": 1.5,
    "Regular Hours": 255.9,
    "Overtime Hours": 14.7,
    "Total Regular Pay": 6899,
    "Total Overtime Pay": 594,
    "Run Volume": 187,
    "Avg Cost Per Transport": 1579,
    "Total Revenue": 205748,
    "PEMT Supplement": 81198,
    "Dispatch Time (sec)": 45,
    "Response Time (min)": 29.8,
    "Scene Time (min)": 40,
    "Transport Time (min)": 9.4
  },
  {
    "Employee ID": "EMP-118",
    "Month": "May 2026",
    "Job Title": "Paramedic",
    "Call Source": "Disaster Response",
    "FTE Count": 0.8,
    "Regular Hours": 126.2,
    "Overtime Hours": 45.6,
    "Total Regular Pay": 4192,
    "Total Overtime Pay": 2272,
    "Run Volume": 51,
    "Avg Cost Per Transport": 916,
    "Total Revenue": 34908,
    "PEMT Supplement": 9513,
    "Dispatch Time (sec)": 87,
    "Response Time (min)": 35.8,
    "Scene Time (min)": 20.8,
    "Transport Time (min)": 16.1
  },
  {
    "Employee ID": "EMP-101",
    "Month": "June 2026",
    "Job Title": "Captain/Shift Supervisor",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 1.2,
    "Regular Hours": 192.9,
    "Overtime Hours": 39.2,
    "Total Regular Pay": 10255,
    "Total Overtime Pay": 3126,
    "Run Volume": 172,
    "Avg Cost Per Transport": 212,
    "Total Revenue": 30728,
    "PEMT Supplement": 8157,
    "Dispatch Time (sec)": 262,
    "Response Time (min)": 24.3,
    "Scene Time (min)": 26.6,
    "Transport Time (min)": 32.8
  },
  {
    "Employee ID": "EMP-103",
    "Month": "June 2026",
    "Job Title": "Dispatcher",
    "Call Source": "Interfacility Transfer",
    "FTE Count": 0.5,
    "Regular Hours": 82.8,
    "Overtime Hours": 0,
    "Total Regular Pay": 1519,
    "Total Overtime Pay": 0,
    "Run Volume": 56,
    "Avg Cost Per Transport": 525,
    "Total Revenue": 24452,
    "PEMT Supplement": 5520,
    "Dispatch Time (sec)": 164,
    "Response Time (min)": 10.9,
    "Scene Time (min)": 26.1,
    "Transport Time (min)": 34.7
  },
  {
    "Employee ID": "EMP-108",
    "Month": "June 2026",
    "Job Title": "EMT-Basic",
    "Call Source": "Disaster Response",
    "FTE Count": 1.5,
    "Regular Hours": 242.1,
    "Overtime Hours": 18.9,
    "Total Regular Pay": 5070,
    "Total Overtime Pay": 594,
    "Run Volume": 160,
    "Avg Cost Per Transport": 1775,
    "Total Revenue": 178832,
    "PEMT Supplement": 75247,
    "Dispatch Time (sec)": 94,
    "Response Time (min)": 45,
    "Scene Time (min)": 37.5,
    "Transport Time (min)": 35.1
  },
  {
    "Employee ID": "EMP-105",
    "Month": "June 2026",
    "Job Title": "EMT-Basic",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 0.8,
    "Regular Hours": 126.7,
    "Overtime Hours": 23.4,
    "Total Regular Pay": 2815,
    "Total Overtime Pay": 780,
    "Run Volume": 36,
    "Avg Cost Per Transport": 924,
    "Total Revenue": 24595,
    "PEMT Supplement": 9428,
    "Dispatch Time (sec)": 77,
    "Response Time (min)": 5.7,
    "Scene Time (min)": 32.8,
    "Transport Time (min)": 40.6
  },
  {
    "Employee ID": "EMP-104",
    "Month": "June 2026",
    "Job Title": "EMT-Basic",
    "Call Source": "911 Emergency Medical",
    "FTE Count": 1.5,
    "Regular Hours": 254.4,
    "Overtime Hours": 19.7,
    "Total Regular Pay": 5934,
    "Total Overtime Pay": 689,
    "Run Volume": 207,
    "Avg Cost Per Transport": 1108,
    "Total Revenue": 150608,
    "PEMT Supplement": 68762,
    "Dispatch Time (sec)": 61,
    "Response Time (min)": 6.5,
    "Scene Time (min)": 39.4,
    "Transport Time (min)": 45.7
  },
  {
    "Employee ID": "EMP-106",
    "Month": "June 2026",
    "Job Title": "Firefighter/EMT",
    "Call Source": "Standby / Non-Emergency",
    "FTE Count": 0.8,
    "Regular Hours": 132.4,
    "Overtime Hours": 0,
    "Total Regular Pay": 3470,
    "Total Overtime Pay": 0,
    "Run Volume": 55,
    "Avg Cost Per Transport": 228,
    "Total Revenue": 8681,
    "PEMT Supplement": 2832,
    "Dispatch Time (sec)": 140,
    "Response Time (min)": 19,
    "Scene Time (min)": 14.4,
    "Transport Time (min)": 11.8
  },
  {
    "Employee ID": "EMP-118",
    "Month": "June 2026",
    "Job Title": "Paramedic",
    "Call Source": "Critical Care Transport",
    "FTE Count": 0.5,
    "Regular Hours": 82.6,
    "Overtime Hours": 7.4,
    "Total Regular Pay": 3094,
    "Total Overtime Pay": 416,
    "Run Volume": 79,
    "Avg Cost Per Transport": 2211,
    "Total Revenue": 141495,
    "PEMT Supplement": 27676,
    "Dispatch Time (sec)": 45,
    "Response Time (min)": 9.6,
    "Scene Time (min)": 15.5,
    "Transport Time (min)": 42.3
  }
];

export const getMockWorkbook = (fileName: string): WorkbookData => {
  if (fileName.includes('High Variation') || fileName.includes('high_variation')) {
    return createMockWorkbook('High Variation Operations', highVariationRows);
  }
  if (fileName.includes('PEMT Data')) {
    return createMockWorkbook('PEMT Reimbursement Summary', pemtRows);
  }
  if (fileName.includes('Personnel Hours')) {
    return createMockWorkbook('Personnel Expenses', personnelRows);
  }
  if (fileName.includes('Arrival Time') || fileName.includes('CAD Data')) {
    return createMockWorkbook('CAD Responses', cadRows);
  }
  // Default fallback PEMT Data
  return createMockWorkbook('PEMT Reimbursement Summary', pemtRows);
};
